class Autogenerated {
  String? temperature;
  String? humidity;
  String? soilMoisture;
  String? phValue;
  bool? chemical;
  bool? motor;

  Autogenerated(
      {this.temperature,
      this.humidity,
      this.soilMoisture,
      this.phValue,
      this.chemical,
      this.motor});

  Autogenerated.fromJson(Map json) {
    temperature = json['temperature'];
    humidity = json['humidity'];
    soilMoisture = json['soil_moisture'];
    phValue = json['ph_value'];
    chemical = json['chemical'];
    motor = json['motor'];
  }

  Map toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['temperature'] = this.temperature;
    data['humidity'] = this.humidity;
    data['soil_moisture'] = this.soilMoisture;
    data['ph_value'] = this.phValue;
    data['chemical'] = this.chemical;
    data['motor'] = this.motor;
    return data;
  }
}
